/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace StuffERC721 {
	export type Oklch = {
		lightness: number;
		chroma: number;
		hue: number;
	};
	export type Stuff = {
		authorName: string;
		authorAddress: Address;
		title: string;
		description: string;
		creationDate: bigint;
		canvas: Bytes;
	};
	export type StuffParams = {
		authorName: string;
		title: string;
		description: string;
		canvas: Bytes;
	};
}
