/* Auto-generated by contracts/ts/script.ts (libs). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace Actors {
	export type Actor = {
		name: string;
		index: number;
		pk: bigint;
		addr: Address;
	};
}

export namespace IMulticall3 {
	export type Call = {
		target: Address;
		callData: Bytes;
	};
	export type Call3 = {
		target: Address;
		allowFailure: boolean;
		callData: Bytes;
	};
	export type Call3Value = {
		target: Address;
		allowFailure: boolean;
		value: bigint;
		callData: Bytes;
	};
	export type Result = {
		success: boolean;
		returnData: Bytes;
	};
}

export namespace Math {
	export enum Rounding {
		Floor = 0,
		Ceil = 1,
		Trunc = 2,
		Expand = 3,
	}
}

export namespace StdChains {
	export type Chain = {
		name: string;
		chainId: bigint;
		chainAlias: string;
		rpcUrl: string;
	};
	export type ChainData = {
		name: string;
		chainId: bigint;
		rpcUrl: string;
	};
}

export namespace StdCheatsSafe {
	export enum AddressType {
		Payable = 0,
		NonPayable = 1,
		ZeroAddress = 2,
		Precompile = 3,
		ForgeAddress = 4,
	}
	export type AccessList = {
		accessAddress: Address;
		storageKeys: Array<Bytes>;
	};
	export type Account = {
		addr: Address;
		key: bigint;
	};
	export type EIP1559ScriptArtifact = {
		libraries: Array<string>;
		path: string;
		pending: Array<string>;
		receipts: Array<StdCheatsSafe.Receipt>;
		timestamp: bigint;
		transactions: Array<StdCheatsSafe.Tx1559>;
		txReturns: Array<StdCheatsSafe.TxReturn>;
	};
	export type RawEIP1559ScriptArtifact = {
		libraries: Array<string>;
		path: string;
		pending: Array<string>;
		receipts: Array<StdCheatsSafe.RawReceipt>;
		txReturns: Array<StdCheatsSafe.TxReturn>;
		timestamp: bigint;
		transactions: Array<StdCheatsSafe.RawTx1559>;
	};
	export type RawReceipt = {
		blockHash: Bytes;
		blockNumber: Bytes;
		contractAddress: Address;
		cumulativeGasUsed: Bytes;
		effectiveGasPrice: Bytes;
		from: Address;
		gasUsed: Bytes;
		logs: Array<StdCheatsSafe.RawReceiptLog>;
		logsBloom: Bytes;
		status: Bytes;
		to: Address;
		transactionHash: Bytes;
		transactionIndex: Bytes;
	};
	export type RawReceiptLog = {
		logAddress: Address;
		blockHash: Bytes;
		blockNumber: Bytes;
		data: Bytes;
		logIndex: Bytes;
		removed: boolean;
		topics: Array<Bytes>;
		transactionHash: Bytes;
		transactionIndex: Bytes;
		transactionLogIndex: Bytes;
	};
	export type RawTx1559 = {
		arguments: Array<string>;
		contractAddress: Address;
		contractName: string;
		functionSig: string;
		hash: Bytes;
		txDetail: StdCheatsSafe.RawTx1559Detail;
		opcode: string;
	};
	export type RawTx1559Detail = {
		accessList: Array<StdCheatsSafe.AccessList>;
		data: Bytes;
		from: Address;
		gas: Bytes;
		nonce: Bytes;
		to: Address;
		txType: Bytes;
		value: Bytes;
	};
	export type Receipt = {
		blockHash: Bytes;
		blockNumber: bigint;
		contractAddress: Address;
		cumulativeGasUsed: bigint;
		effectiveGasPrice: bigint;
		from: Address;
		gasUsed: bigint;
		logs: Array<StdCheatsSafe.ReceiptLog>;
		logsBloom: Bytes;
		status: bigint;
		to: Address;
		transactionHash: Bytes;
		transactionIndex: bigint;
	};
	export type ReceiptLog = {
		logAddress: Address;
		blockHash: Bytes;
		blockNumber: bigint;
		data: Bytes;
		logIndex: bigint;
		topics: Array<Bytes>;
		transactionIndex: bigint;
		transactionLogIndex: bigint;
		removed: boolean;
	};
	export type Tx1559 = {
		arguments: Array<string>;
		contractAddress: Address;
		contractName: string;
		functionSig: string;
		hash: Bytes;
		txDetail: StdCheatsSafe.Tx1559Detail;
		opcode: string;
	};
	export type Tx1559Detail = {
		accessList: Array<StdCheatsSafe.AccessList>;
		data: Bytes;
		from: Address;
		gas: bigint;
		nonce: bigint;
		to: Address;
		txType: bigint;
		value: bigint;
	};
	export type TxDetailLegacy = {
		accessList: Array<StdCheatsSafe.AccessList>;
		chainId: bigint;
		data: Bytes;
		from: Address;
		gas: bigint;
		gasPrice: bigint;
		hash: Bytes;
		nonce: bigint;
		opcode: Bytes;
		r: Bytes;
		s: Bytes;
		txType: bigint;
		to: Address;
		v: number;
		value: bigint;
	};
	export type TxLegacy = {
		arguments: Array<string>;
		contractAddress: Address;
		contractName: string;
		functionSig: string;
		hash: string;
		opcode: string;
		transaction: StdCheatsSafe.TxDetailLegacy;
	};
	export type TxReturn = {
		internalType: string;
		value: string;
	};
}

export namespace VmSafe {
	export enum AccountAccessKind {
		Call = 0,
		DelegateCall = 1,
		CallCode = 2,
		StaticCall = 3,
		Create = 4,
		SelfDestruct = 5,
		Resume = 6,
		Balance = 7,
		Extcodesize = 8,
		Extcodehash = 9,
		Extcodecopy = 10,
	}
	export enum BroadcastTxType {
		Call = 0,
		Create = 1,
		Create2 = 2,
	}
	export enum CallerMode {
		None = 0,
		Broadcast = 1,
		RecurrentBroadcast = 2,
		Prank = 3,
		RecurrentPrank = 4,
	}
	export enum ForgeContext {
		TestGroup = 0,
		Test = 1,
		Coverage = 2,
		Snapshot = 3,
		ScriptGroup = 4,
		ScriptDryRun = 5,
		ScriptBroadcast = 6,
		ScriptResume = 7,
		Unknown = 8,
	}
	export type AccessListItem = {
		target: Address;
		storageKeys: Array<Bytes>;
	};
	export type AccountAccess = {
		chainInfo: VmSafe.ChainInfo;
		kind: VmSafe.AccountAccessKind;
		account: Address;
		accessor: Address;
		initialized: boolean;
		oldBalance: bigint;
		newBalance: bigint;
		deployedCode: Bytes;
		value: bigint;
		data: Bytes;
		reverted: boolean;
		storageAccesses: Array<VmSafe.StorageAccess>;
		depth: bigint;
		oldNonce: bigint;
		newNonce: bigint;
	};
	export type BroadcastTxSummary = {
		txHash: Bytes;
		txType: VmSafe.BroadcastTxType;
		contractAddress: Address;
		blockNumber: bigint;
		success: boolean;
	};
	export type Chain = {
		name: string;
		chainId: bigint;
		chainAlias: string;
		rpcUrl: string;
	};
	export type ChainInfo = {
		forkId: bigint;
		chainId: bigint;
	};
	export type DebugStep = {
		stack: Array<bigint>;
		memoryInput: Bytes;
		opcode: number;
		depth: bigint;
		isOutOfGas: boolean;
		contractAddr: Address;
	};
	export type DirEntry = {
		errorMessage: string;
		path: string;
		depth: bigint;
		isDir: boolean;
		isSymlink: boolean;
	};
	export type EthGetLogs = {
		emitter: Address;
		topics: Array<Bytes>;
		data: Bytes;
		blockHash: Bytes;
		blockNumber: bigint;
		transactionHash: Bytes;
		transactionIndex: bigint;
		logIndex: bigint;
		removed: boolean;
	};
	export type FfiResult = {
		exitCode: number;
		stdout: Bytes;
		stderr: Bytes;
	};
	export type FsMetadata = {
		isDir: boolean;
		isSymlink: boolean;
		length: bigint;
		readOnly: boolean;
		modified: bigint;
		accessed: bigint;
		created: bigint;
	};
	export type Gas = {
		gasLimit: bigint;
		gasTotalUsed: bigint;
		gasMemoryUsed: bigint;
		gasRefunded: bigint;
		gasRemaining: bigint;
	};
	export type Log = {
		topics: Array<Bytes>;
		data: Bytes;
		emitter: Address;
	};
	export type PotentialRevert = {
		reverter: Address;
		partialMatch: boolean;
		revertData: Bytes;
	};
	export type Rpc = {
		key: string;
		url: string;
	};
	export type SignedDelegation = {
		v: number;
		r: Bytes;
		s: Bytes;
		nonce: bigint;
		implementation: Address;
	};
	export type StorageAccess = {
		account: Address;
		slot: Bytes;
		isWrite: boolean;
		previousValue: Bytes;
		newValue: Bytes;
		reverted: boolean;
	};
	export type Wallet = {
		addr: Address;
		publicKeyX: bigint;
		publicKeyY: bigint;
		privateKey: bigint;
	};
}
