/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace PantoneRegistry {
	export type Pantone = {
		pantone: string;
		hexValue: string;
		cmyk: string;
		exists: boolean;
	};
}

export namespace StuffCollectionERC721 {
	export type MintAuthorization = {
		from: Address;
		validAfter: bigint;
		validBefore: bigint;
		nonce: Bytes;
		v: number;
		r: Bytes;
		s: Bytes;
	};
	export type StuffCollection = {
		sku: string;
		category: string;
		metadataURI: string;
		options: Array<Array<string>>;
		paymentToken: Address;
		paymentRecipient: Address;
		maxSupply: bigint;
		mintPriceToken: bigint;
	};
	export type StuffItem = {
		id: bigint;
		author: string;
		authorAddress: Address;
		title: string;
		description: string;
		creationDate: bigint;
		canvas: Array<string>;
		options: Array<Array<string>>;
	};
	export type StuffItemMintParams = {
		author: string;
		title: string;
		description: string;
		canvas: Array<string>;
		options: Array<Array<string>>;
	};
}
