/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace StuffERC721 {
	export type MintAuthorization = {
		from: Address;
		validAfter: bigint;
		validBefore: bigint;
		nonce: Bytes;
		v: number;
		r: Bytes;
		s: Bytes;
	};
	export type Stuff = {
		author: string;
		authorAddress: Address;
		title: string;
		description: string;
		creationDate: bigint;
		canvas: Bytes;
		options: Array<Array<string>>;
	};
	export type StuffCollection = {
		sku: string;
		category: string;
		metadataURI: string;
		palette: Array<string>;
		options: Array<Array<string>>;
		paymentToken: Address;
		paymentRecipient: Address;
		maxSupply: bigint;
		mintPriceToken: bigint;
	};
	export type StuffMintParams = {
		author: string;
		title: string;
		description: string;
		canvas: Bytes;
		options: Array<Array<string>>;
	};
}
