"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Untitled.glb --transform --types 
Files: Untitled.glb [19.35MB] > /Users/sshmaxime/Workspace/buidlerhq/apps/stuff/Untitled-transformed.glb [1.05MB] (95%)
*/

const MODEL_PATH = "/models/stuff-00000.glb";

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import { useEffect, useMemo } from "react";
import type * as THREE from "three";
import {
	BufferAttribute,
	CanvasTexture,
	ClampToEdgeWrapping,
	NearestFilter,
	SRGBColorSpace,
	Vector3,
} from "three";
import type { GLTF } from "three-stdlib";
import { useProductConfiguratorStore } from "@/features/product-configurator/store";

type GLTFResult = GLTF & {
	nodes: {
		T_Shirt: THREE.Mesh;
		Embroidery_Patch: THREE.Mesh;
	};
	materials: {
		T_Shirt_Material: THREE.MeshStandardMaterial;
		Embroidery_Area: THREE.MeshStandardMaterial;
	};
	animations: THREE.AnimationClip[];
};

type ModelProps = JSX.IntrinsicElements["group"] & {
	sku?: string;
};

const createProjectedPatchGeometry = (source: THREE.BufferGeometry) => {
	const geometry = source.clone();
	geometry.computeBoundingBox();

	const positionAttribute = geometry.getAttribute("position");
	const boundingBox = geometry.boundingBox;

	if (!positionAttribute || !boundingBox) {
		return geometry;
	}

	const size = boundingBox.getSize(new Vector3());
	const axes = [
		{ axis: 0, size: size.x },
		{ axis: 1, size: size.y },
		{ axis: 2, size: size.z },
	].sort((left, right) => right.size - left.size);

	const [uAxis, vAxis] = axes;
	const uMin = boundingBox.min.getComponent(uAxis.axis);
	const vMin = boundingBox.min.getComponent(vAxis.axis);
	const uSize = Math.max(uAxis.size, Number.EPSILON);
	const vSize = Math.max(vAxis.size, Number.EPSILON);
	const uv = new Float32Array(positionAttribute.count * 2);

	for (let index = 0; index < positionAttribute.count; index++) {
		const uValue = positionAttribute.getComponent(index, uAxis.axis);
		const vValue = positionAttribute.getComponent(index, vAxis.axis);

		uv[index * 2] = (uValue - uMin) / uSize;
		uv[index * 2 + 1] = 1 - (vValue - vMin) / vSize;
	}

	geometry.setAttribute("uv", new BufferAttribute(uv, 2));

	return geometry;
};

export function Model({ sku, ...props }: ModelProps) {
	const configuration = useProductConfiguratorStore((state) =>
		sku ? state.configurationsBySku[sku] : undefined,
	);
	const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult;
	const patchGeometry = useMemo(
		() => createProjectedPatchGeometry(nodes.Embroidery_Patch.geometry),
		[nodes.Embroidery_Patch.geometry],
	);
	const patchTexture = useMemo(() => {
		if (!configuration?.design) {
			return null;
		}

		const { pixels, size } = configuration.design;
		const canvas = document.createElement("canvas");
		canvas.width = size;
		canvas.height = size;

		const context = canvas.getContext("2d");
		if (!context) {
			return null;
		}

		pixels.forEach((color, index) => {
			context.fillStyle = color;
			context.fillRect(index % size, Math.floor(index / size), 1, 1);
		});

		const texture = new CanvasTexture(canvas);
		texture.colorSpace = SRGBColorSpace;
		texture.flipY = false;
		texture.generateMipmaps = false;
		texture.magFilter = NearestFilter;
		texture.minFilter = NearestFilter;
		texture.wrapS = ClampToEdgeWrapping;
		texture.wrapT = ClampToEdgeWrapping;
		texture.needsUpdate = true;

		return texture;
	}, [configuration]);

	useEffect(() => {
		return () => {
			patchTexture?.dispose();
		};
	}, [patchTexture]);

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.T_Shirt.geometry}
				material={materials.T_Shirt_Material}
				position={[0, -1.305, 0]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={patchGeometry}
				position={[0, 0, -0.2]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[0.14, 1, 0.14]}
			>
				<meshStandardMaterial
					color="#ffffff"
					map={patchTexture ?? undefined}
					metalness={materials.Embroidery_Area.metalness}
					metalnessMap={materials.Embroidery_Area.metalnessMap}
					normalMap={materials.Embroidery_Area.normalMap}
					normalScale={materials.Embroidery_Area.normalScale}
					roughness={materials.Embroidery_Area.roughness}
					roughnessMap={materials.Embroidery_Area.roughnessMap}
				/>
			</mesh>
		</group>
	);
}

useGLTF.preload(MODEL_PATH);
