import { CANVAS_SIZE } from "@/features/grid/utils";

type GridTemplateSource = {
	id: string;
	name: string;
	description: string;
	canvas: string[][];
};

const SUNFLOWER_TEMPLATE_LEGEND = {
	A: "15-4421 TCX",
	B: "19-4052 TCX",
	C: "19-4024 TCX",
	D: "17-4728 TCX",
	E: "14-0848 TCX",
	F: "13-0647 TCX",
	G: "14-0957 TCX",
	H: "18-4032 TCX",
	I: "19-3911 TCX",
	J: "16-1364 TCX",
	K: "16-0948 TCX",
	L: "19-5513 TCX",
	M: "19-0820 TCX",
	N: "19-0809 TCX",
	O: "15-0850 TCX",
	P: "18-0830 TCX",
	Q: "19-0915 TCX",
	R: "18-1140 TCX",
	S: "16-0952 TCX",
	T: "18-1449 TCX",
	U: "15-0343 TCX",
	V: "16-4535 TCX",
} as const;

const SUNFLOWER_TEMPLATE_ROWS = [
	"AABAAAAAAAAAAAAAAAAAAAAAAAACAAAAADAAAAAAAA",
	"AABAAAAAAAAAAAAAAAAAAAAAAAACAAAAADAAAAAAAA",
	"AABAAAAADAAAAAAAAAAAAAEAAAACAAAAADAAAAAAAA",
	"AABAAAAADAAAAAAAEAAAEEFGAAACAAAAADAAAAAAAA",
	"AABAAAAADAAAAAAAEAAAEEFGAAACAAAAADAAAAAAAA",
	"AACAAAAADAAAAAAAEHAAEEFGAAACAAAAADAAAAAAAA",
	"AABAAAAADAAAAAEEFEGAEEEEGAGIEEAAADAAAAAAAA",
	"AACAAAAADAEEGAGGEEGGEEEEGGEIEEAAADAAAAAAAA",
	"AACAAAAADAEEGAGGEEGGEEEEGGEIEEAAADAAAAAAAA",
	"AABAAAAADAEFFGJGEEEGEEEEJEEIEGAAADAAAAAAAA",
	"AABAAAAADAGEEEEEGEEJEEEEJEEIEGAEEGEAAAAAAA",
	"AABAAAAADAGEEEEEGEEJEEEEJEEIEGAEEGEAAAAAAA",
	"AACAAAAADAAEEEEEGGEGGEEJEEEIGGEEEKEAAAAAAA",
	"CCICCCCCILCIIMMMINIIIIINIININIIMIINCCCCCCC",
	"AACAAAEEGEGGEEEEEJENOONJEEGIGEEEEKGAAAAAAA",
	"AACAAAEEGEGGEEEEEJENOONJEEGIGEEEEKGAAAAAAA",
	"AACAAAFEFFEEGGEGENNPQQPNNGJIEEEEGDAAAAAAAA",
	"AABAAAOEGEEEEGGGNPRRPPRRPNGIEEEGGKGEAAAAAA",
	"AABAAAOEGEEEEGGGNPRRPPRRPNGIEEEGGKGEAAAAAA",
	"AACAAAAGGEEEEENNPRPINNINRPNIEGGGEGFFEAAAAA",
	"AABAAASGKGGGGNQMRNIQIIQINRQINGEEEGEEGAAAAA",
	"AACAAFEEGEEEJNRRPININNINIPRINEEEEKEGAAAAAA",
	"AACAAFEEGEEEJNRRPININNINIPRINEEEEKEGAAAAAA",
	"AACAAEEEGEEEGNRTPININNINIMRIMEEEEKEGAAAAAA",
	"AACAAGEEGEEEENRRPQINIINIQNRINGGEGKGAAAAAAA",
	"AACAAGEEGEEEENRRPQINIINIQNRINGGEGKGAAAAAAA",
	"AABAAAGEGEGJNMRRPIQINIINIPRINNGGGKEEAAAAAA",
	"AACAAAAJKJEGENRRNQIQIINIQNRINGEEEGEFEAAAAA",
	"AACAAAGEGEEEENPPRIQINNIQIRPINGEEEKEEJAAAAA",
	"AACAAAGEGEEEENPPRIQINNIQIRPINGEEEKEEJAAAAA",
	"AACAAEEEGEEEGJNNPRIQIIPIRPNIJGGJGKGJAAAAAA",
	"BBLBBMPPPPPPPPPPIINIINIIIIIIPPPPPNBBBBBBBB",
	"BBLBBMPPPPPPPPPPIINIINIIIIIIPPPPPNBBBBBBBB",
	"AABAAOEEGEEGGEJJNPRNPPNRPNNIEEEEJDAAAAAAAA",
	"AACAAAAALLMLLUMMMMAAMMLAAMMIMULLMLMAAAAAAA",
	"AACAAAAALLMLLUMMMMAAMMLAAMMIMULLMLMAAAAAAA",
	"AACAAAAALLMLLUMMMMAAMMLAAMMIMULLMLMAAAAAAA",
	"AABAAAAAVALLMMLLLMMAMMLAMMLILMMLLDAAAAAAAA",
	"AACAAAAADAAALLLLLALLMMLMLALILLLAADAAAAAAAA",
	"AACAAAAADAAALLLLLALLMMLMLALILLLAADAAAAAAAA",
	"AABAAAAAAAAAAAAAAAALMMLLAAACAAAAADAAAAAAAA",
	"AACAAAAAVAAAAAAAAAAMMMLMAAACAAAAADAAAAAAAA",
] as const;

const decodeTemplateRows = (
	rows: readonly string[],
	legend: Record<string, string>,
): string[][] => {
	if (rows.length !== CANVAS_SIZE) {
		throw new Error(`Template row count must be ${CANVAS_SIZE}. Received ${rows.length}.`);
	}

	return rows.map((row) => {
		if (row.length !== CANVAS_SIZE) {
			throw new Error(`Template column count must be ${CANVAS_SIZE}. Received ${row.length}.`);
		}

		return row.split("").map((symbol) => {
			const pantone = legend[symbol];
			if (!pantone) {
				throw new Error(`Missing Pantone legend entry for symbol "${symbol}".`);
			}
			return pantone;
		});
	});
};

const gridTemplateLibrary: GridTemplateSource[] = [
	{
		id: "sunflower",
		name: "Sunflower",
		description: "Scaled from the uploaded sunflower artwork and mapped to the nearest seeded Pantones.",
		canvas: decodeTemplateRows(SUNFLOWER_TEMPLATE_ROWS, SUNFLOWER_TEMPLATE_LEGEND),
	},
];

export type { GridTemplateSource };
export { gridTemplateLibrary };
